### ISSUE TITLE
Add support for monorepo packages

### ISSUE THREAD

**Issue by steelbrain** [vercel/nft#166]
In monorepo yarn workspace packages, for a package at `./packages/x` the dependencies are often at `./node_modules`

This is blacklisted in https://github.com/vercel/nft/blob/dc198266f241e863113f8970c5f82695b6237950/src/node-file-trace.ts#L87

Thoughts on adding an `ignore` opt in `NodeFileTraceOptions` that overrides the default and allows specific parent deps for people who need it?

**Comment by styfle** [comment]
You'll need to set `base` and possibly `processCwd` if you want to include directories above the current working directory.

See [the docs](https://github.com/vercel/nft#options) for examples.

**Comment by steelbrain** [comment]
Thanks for the directions @styfle. They make sense!
