### ISSUE TITLE
Cannot trace dynamic require of the createsend-node module

### ISSUE THREAD

**Issue by nkzawa** [vercel/nft#175]
https://github.com/nufyoot/createsend-node

```
// index.js
var libPath = process.env['CREATESEND_NODE_COV'] ? './lib-cov' : './lib';

module.exports = require(libPath + '/createsend');
```

Seems the problem was solved by the commit https://github.com/nufyoot/createsend-node/commit/b75a8b88979e928b3276d15e87bcab54994780eb, but it's not released to npm.

**Comment by styfle** [comment]
@guybedford Is this something we can fix?

At best, we could include detect both requires for `./lib-cov/createsend.js' and `./lib/createsend.js'

**Comment by guybedford** [comment]
This could be done, but it isn't a simple fix for the current analysis unfortunately.

We do support branch analysis and we do support these variable analyses, but we specifically currently disable branch analysis on variable declaration analysis to try to reduce the performance overhead of the analysis.

I could try enabling it and see how that goes, and that would certainly fix the issue. It would be a little work to extend the branch analysis to the variable analysis but it would be fine. My concern though is just limiting the perf overhead.

We can certainly investigate - it's a very natural extension of the current primitives (at its core changing the branch analysis is literally a boolean flag).

**Comment by guybedford** [comment]
Implemented in https://github.com/vercel/nft/pull/181.
