### ISSUE TITLE
Add support for `top-level await`

### ISSUE THREAD

**Issue by hehex9** [vercel/nft#188]
just noticed an Error in `warnings`:
```
Error: Failed to parse xxx.js as module:
Cannot use keyword 'await' outside an async function
    at Object.analyze [as default] ...
```

it already supported in node>=14.8.0, so i think there will be more and more projects using top-level await in the future.

**Comment by styfle** [comment]
Looks like we need to pass [allowAwaitOutsideFunction](https://github.com/acornjs/acorn/tree/master/acorn#interface) to acorn.

Would you like to submit a PR with a test to fix this?
