### ISSUE TITLE
Exclude list?

### ISSUE THREAD

**Issue by janpio** [vercel/nft#202]
Is there a way to influence `@vercel/nft` from the outside by providing a list of paths or files to _ignore_ or _exclude_ from the function dist, even though `nft` itself would decide to include it? 

Unfortunately we sometimes have bugs (or unintended features) in Prisma that lead to big files wrongly being considered required, and then included in the serverless functions. This can also be triggerd by accident by users doing things in their codebase. Sometimes this even leads to the function archive getting to big for Vercel to upload it to AWS Lambda.

An exclude list would be a good workaround we could give our users temporarily to manually exclude some files or folders and unblock their deployments to Vercel functions.

**Comment by styfle** [comment]
There is an `ignore` option you can use here:

https://github.com/vercel/nft/blob/main/readme.md#ignore

**Comment by janpio** [comment]
When I am the user of `@vercel/nft` myself that works, but can I influence that list when just deploying to Vercel (which uses `@vercel/nft` under the hood of course)? I would like to be able to tell a user "put this at x to make sure e.g. `@primsa/engines` is never included in your serverless function". Optimally I as a library/dependency author could do the same.

(Serverless Framework for example supports patterns that define what to include or exclude from a "package": https://www.serverless.com/framework/docs/providers/aws/guide/packaging/)

**Comment by styfle** [comment]
Vercel deployments are typically zero config so we don't want to instruct every user to add config.

I think its best to solve it once in the package (#203) than to make every user add config.

**Comment by styfle** [comment]
This also might be a good use case for [`conditions`](https://nodejs.org/api/packages.html#packages_resolving_user_conditions) so the `@primsa/engines` package can declare different exports for development vs production.

**Comment by styfle** [comment]
I'm going to close this issue since `nft` already supports this use case though [ignore](https://github.com/vercel/nft/blob/main/readme.md#ignore) option.

Let me know if there is anything else we need here 👍

**Comment by lobsterkatie** [comment]
> Vercel deployments are typically zero config so we don't want to instruct every user to add config.
> 
> I think its best to solve it once in the package (#203) than to make every user add config.

I agree that we don't want users to have to add config, but it would be nice if libraries could. One option would be to have NFT pick up on any files listed in webpack's `external` option, as that's literally someone saying "please don't bundle this."
