### ISSUE TITLE
Failing builds on Vercel 

### ISSUE THREAD

**Issue by benjamintd** [vercel/nft#210]
I'm seeing an issue in my Vercel builds that I _think_ are due to a bug introduced by #205  (cc @guybedford): 

```
10:48:44.919 | TypeError: Cannot read property 'type' of undefined
-- | --
10:48:44.920 | at Object.handleWrappers (/vercel/c867bd80ceadca61/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:154224)
10:48:44.920 | at Object.analyze (/vercel/c867bd80ceadca61/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:102422)
10:48:44.920 | at Job.emitDependency (/vercel/c867bd80ceadca61/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:115851)
10:48:44.920 | at /vercel/c867bd80ceadca61/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:116609
10:48:44.920 | at Array.map (&lt;anonymous&gt;)
10:48:44.920 | at Job.emitDependency (/vercel/c867bd80ceadca61/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:116308)
10:48:44.920 | at runMicrotasks (&lt;anonymous&gt;)
10:48:44.920 | at processTicksAndRejections (internal/process/task_queues.js:93:5)
10:48:44.920 | at /vercel/c867bd80ceadca61/.build-utils/.builder/node_modules/@vercelruntimes/next/dist/index.js:1:116598
10:48:44.920 | at async Promise.all (index 2)
```

The timing and function names seem to coincide (builds have been failing since last Friday). Unfortunately the line numbers provided by the trace are not helpful to determine exactly where the bug is, and I am not familiar enough with the library to provide a fix or even a failing test case.

It seems though that the bug was introduced somewhere in [this diff](https://github.com/vercel/nft/commit/0b4fa909bbdfcec854dd1416af71f3c1ee834354#diff-a18ef75547da46748f7684730fa47084fab2e3a13d5d5a2c2a90a8df70b9b04b).

I have opened a support case with Vercel but I figured that it could be helpful to raise the issue directly in the relevant repo.

**Comment by guybedford** [comment]
Thanks for posting, it's more likely this could have been caused by https://github.com/vercel/nft/commit/0b4fa909bbdfcec854dd1416af71f3c1ee834354. Do you have a replication to share?

**Comment by guybedford** [comment]
@benjamintd the check that it is an ExpressionStatement guarantees it has an expression property. I double checked the PR and they're definitely all guarded as far as I can tell. Unfortunately without a replication there's not a lot more I can do.

**Comment by benjamintd** [comment]
Thanks @guybedford, it makes sense. I tried to reproduce locally but I was not able to do so. I have no idea where this library is invoked inside the Vercel toolchain which makes it harder to identify the problem. 

I'll wait for the Vercel support team to reply to my ticket and keep you up to date in case I find something in the meantime. Thanks for looking.

**Comment by benjamintd** [comment]
The issue is indeed fixed. Thank you for the fix @styfle !
