### ISSUE TITLE
Cannot deploy Playwright to Vercel - required file not traced by NFT

### ISSUE THREAD

**Issue by juice49** [vercel/nft#211]
Playwright cannot be deployed to Vercel since @vercel/nft 0.12.0 was released. This was previously working with @vercel/nft 0.11.2.

Playwright [requires a file named `browsers.json`](https://github.com/microsoft/playwright/blob/9cd89ae0525b327ce435ae3e4aadcba035621ee9/src/utils/registry.ts#L261), which is not being traced by @vercel/nft 0.12.0.

[This repo has a test case for both 0.11.2 (working) and 0.12.0 (not working)](https://github.com/juice49/vercel-nft-playwright-test).

This has also been discussed at microsoft/playwright#5862.

**Comment by guybedford** [comment]
Thanks @juice49 for the replication here. When I run this test though I get both 0.11.2 and 0.12.0 not working in your replication - so I think this may more likely be related to a code change in playwright itself.

I managed to put together the following analysis unit test based on this case:

```js
var __importDefault = (this && this.__importDefault) || function (mod) {
  return (mod && mod.__esModule) ? mod : { "default": mod };
};

const path_1 = __importDefault(require("path"));
const PACKAGE_PATH = path_1.default.join(__dirname, '..', '..');

class Registry {
  constructor (packagePath) {
    const browsersJSON = require(path_1.default.join(packagePath, 'browsers.json'));
    console.log(browsersJSON);
  }
}

var currentPackageRegistry;
if (!currentPackageRegistry)
  currentPackageRegistry = new Registry(PACKAGE_PATH);
```

As you can see from the above, the asset emission analysis is a very involved execution analysis in this case as we don't analyze class instantiations in our analysis (we don't do any indirect execution flow analysis for that matter).

**Comment by juice49** [comment]
Thanks @guybedford. Is class instantiation analysis something you think belongs in NFT (assuming it's possible)?

I'm going to investigate whether there is a way to change this behaviour in Playwright, or a Playwright fork, but this seems like an intentional design decision in that project.

I know Vercel and NFT aims to be zero-config, but it would be quite useful to have an escape hatch for cases like this.

N.B. I wonder why we get different results from the tests. We should both have `playwright-core@1.12.0-next-alpha-may-21-2021` because of the `package-lock.json`.

**Comment by guybedford** [comment]
The tap test is definitely failing however I do it - note that it shows as three tests with the first one passing but the last two failing which are the actual assertions.

**Comment by guybedford** [comment]
If anything, a version change in Playwright itself could be the issue here.

**Comment by juice49** [comment]
I _think_ NFT 0.11.2 is working when I run the tests:

```
npm t -- --reporter specy
```

<img width="474" alt="Screenshot 2021-05-22 at 13 15 33" src="https://user-images.githubusercontent.com/1454914/119226210-e23ce300-baff-11eb-8e1d-5dbd1991106d.png">

I've also tested by logging the matching files traced by NFT, and here's what I see:

```
[0.11.2] [ 'node_modules/playwright-core/browsers.json' ]
[0.12.0] []
```

**Comment by guybedford** [comment]
@juice49 I was finally able to replicate the case and it turns out it was a bug in NFT that this was ever working in the first place! The details are quite complex but I can 100% confirm it was a very odd bug that it was working.

Basically the other approach to make this kind of thing work is to attempt to treat `*/browsers.json` as a glob and try and find where it is, but the problem with this approach is that we have no idea what `*` is so that it could be anywhere on the entire filesystem. That it was filling in the `*` correctly was through a non-sensical analysis path.

I will leave this open to track analysis of this project further, but unfortunately we can't officially call this a regression or fix such a regression.

**Comment by juice49** [comment]
Okay, thanks for investigating @guybedford. I'm going to look into other options, or tweaks that could reasonably be made to Playwright to get it working.

**Comment by mxschmitt** [comment]
Hey, maybe adding a special case for Playwright would work?
See here: https://github.com/vercel/nft/blob/main/src/utils/special-cases.ts

**Comment by styfle** [comment]
Yep that would work. Do you want to submit a PR add a special case with a test?

**Comment by mxschmitt** [comment]
Yup, added both #213.
