### ISSUE TITLE
nft does not  resolve scoped packages with subpath exports

### ISSUE THREAD

**Issue by microsoftly** [vercel/nft#226]
I have a private package `@myNamespace/package` that has exports `logging` and `errors` defined in the `package.json`.

When using the package, you can import the logging or errors modules with `require('@myNamespace/package/logging)` and `require(@myNamespace/package/errors)`.  This works as expected locally.

It looks like nft is looking for an npm module named `@myNamespace/package/logging` and not stripping off the trailing `/logging`

**Comment by guybedford** [comment]
@microsoftly I attempted to replicate the case you described in https://github.com/guybedford/nft-scoped-replication-attempt but am unable to see this behaviour.

Can you perhaps take a look at that and let me know what changes are necessary to see the issue?
