### ISSUE TITLE
Trace entry files without extension

### ISSUE THREAD

**Issue by remorses** [vercel/nft#249]
Currently files passed to `nodeFileTrace` without extension are not traced beacuse of this line

https://github.com/vercel/nft/blob/f146d3cce10ef1bc9af9bea7778152a150c60c88/src/node-file-trace.ts#L40

However it is common for files that end up in .bin directory to not have an extension (and also to have `#!/usr/bin/env node` on top, which already works), these files are still js code but they don't have the 'js' extension

The following will not trace the files dependencies because `next/dist/bin/next` does not have an extension
```ts
await nodeFileTrace([require.resolve('next/dist/bin/next')])
```

**Comment by styfle** [comment]
We might need to peek in the file contents to check if the first line contains a hash bang.

@guybedford Could we remove this `if` statement since it seems like the caller should avoid calling `nodeFileTrace()` for non-JS files, right?

**Comment by guybedford** [comment]
The reason for this is that Node.js in ESM mode doesn't execute files without an extension, although it does in CJS mode.

We could perhaps add an exception for the initial entry point specifically (`isMain` kind of thing, which is fairly common).

**Comment by styfle** [comment]
I think this guard can be removed for input files and we can fail gracefully during parse failures: #294
