### ISSUE TITLE
ENOENT: no such file or directory using geo-tz package

### ISSUE THREAD

**Issue by ErnestBrandi** [vercel/nft#251]
Hi, I have Next.js website developed on Vercel and using the `find` method from the `geo-tz` package. 
But once in production I get `Error: ENOENT: no such file or directory, open '/var/task/node_modules/geo-tz/data/geo.dat'"}`.
Seems like this package is to blame as when I build my project the file is not included in `next-server.js.nft.json` file.
If this is true, should it be treated as a "special-case" ?
Here the file where the error happens : https://github.com/evansiroky/node-geo-tz/blob/master/src/find.ts

**Comment by styfle** [comment]
Sounds like a bug, thanks!

Can you share the usage that causes it to fail?

I tried the following but it worked as expected:

```js
const { find } = require('geo-tz');
console.log(find(47.650499, -122.350070))
```

Here's how it can be tested against nft:

```
npm i -g @vercel/nft
mkdir example
cd example
npm init -y
npm install geo-tz
echo "const { find } = require('geo-tz'); console.log(find(47.650499, -122.350070))" > index.js
nft build
rm -rf node_modules
node dist/index.js
```

**Comment by ErnestBrandi** [comment]
I'm not sure what's going on. Following your example I started playing with the nft command line and when I do `nft print lib/**/* | grep geo-tz`, I can see `node_modules/geo-tz/data/geo.dat` is listed.
But again when I build my project (even locally) using `next build` I cannot see that file listed in the `next-server.js.nft.json` file (I am using `next 12.0.7`).

**Comment by styfle** [comment]
That could be because `**/*` glob is expanded so its going to check every file but perhaps there is a path that is not finding geo.dat when it should.

It would be helpful if you could share the source code that is failing

**Comment by ErnestBrandi** [comment]
I did a repro with a blank project, seems like it's due when you use `find` on the server side.
Just use it in `getServerSideProps` (as for here : https://gitlab.com/leotellier/nft-geotz/-/blob/main/pages/index.js) and start a build.

**Comment by ErnestBrandi** [comment]
I think treating `geo-tz` library as a special case would solve the problem : 
```
'geo-tz'({ id, emitAsset }) {
     if (id.endsWith('geo-tz/dist/geo-tz.js')) {
         emitAsset(path_1.resolve(path_1.dirname(id), '../data/geo.dat'));
     }
},
```

**Comment by styfle** [comment]
Yes that should work, but I want to add an integration test so we don't regress and hopefully be able to fix it properly in the future.

So we need to create the failing example. And when I tried this, it doesn't fail:

```
const { find } = require('geo-tz');
console.log(find(47.650499, -122.350070))
```

**Comment by ErnestBrandi** [comment]
Yep, but as I said it only happens for certain coordinates (as the ones in my previous post, also here is a repro project : https://gitlab.com/leotellier/nft-geotz/-/blob/main/pages/api/geo.js). Be sure to check the last comment (from project owner) in the linked issue on `geo-tz`, it might help you understanding what's going on.

**Comment by styfle** [comment]
Oh I missed that part, thanks!

I see now this code fails:

```js
const { find } = require('geo-tz');
console.log(find(-21.2377437, 55.48997639438238))
```

My guess is that the `dist/geo-tz.js` is mangled and breaks that static analysis.

We have some analysis for these cases in [wrappers.ts](https://github.com/vercel/nft/blob/main/src/utils/wrappers.ts) so if we can determine the bundler and the pattern used, we can probably have a more general fix there.

Otherwise the quick fix is [special-cases.ts](https://github.com/vercel/nft/blob/main/src/utils/special-cases.ts) like you suggested.

**Comment by ErnestBrandi** [comment]
The `wrapper` method is above my skills and knowledge but I can open a PR for the `special-cases` method if you want to.

**Comment by styfle** [comment]
Ok lets start with special cases and add an integration test to ensure its working 👍
