### ISSUE TITLE
resolve v1.21 breaks bundled graceful-fs in nextjs

### ISSUE THREAD

**Issue by benbender** [vercel/nft#257]
As debugged in https://github.com/browserify/resolve/issues/264, `resolve` v1.21 introduces a change in behaviour which in turn breaks `graceful-fs`. A fix in `graceful-fs` is released with v4.2.9, but nft seems to be bundling a lower version. 

As this potentially breaks a lot of `next.js` babel-setups (see f.e. https://github.com/vercel/next.js/issues/33003), a rerelease with the fixed `graceful-fs`-package would be great!

**Comment by ljharb** [comment]
It would also be ideal if this package didn't bundle requireable things at all, so that downstream consumers benefited from automatic in-range version updates for bugfixes (like this one) and security fixes.

**Comment by styfle** [comment]
Can you share the steps to reproduce the issue?

**Comment by benbender** [comment]
"You could use https://github.com/vercel/next.js/tree/canary/examples/with-babel-macros as a quite simple reproduction for testing. Simply clone it and run "npm install && npm dev" to see the error in the browser."

as written here https://github.com/browserify/resolve/issues/264#issuecomment-1005917464

**Comment by ljharb** [comment]
Note that if you update graceful-fs and recreate the bundle, that should be sufficient to solve the short-term problem.

**Comment by styfle** [comment]
So this isn't an issue with `nft` which doesn't rely on `resolve`?

**Comment by ljharb** [comment]
ahhh right, this was filed on the wrong repo (about relying on graceful-fs, not on resolve). It's an issue with the index.js file in https://unpkg.com/browse/next@12.0.7/dist/compiled/@vercel/nft/ which bundles the broken graceful-fs instead of requiring it.

This should be closed and filed instead of the repo for the `next` package.

**Comment by styfle** [comment]
Upon further investigation, I think the issue is the global patch here: https://github.com/vercel/nft/blob/f146d3cce10ef1bc9af9bea7778152a150c60c88/src/node-file-trace.ts#L16

I think we can change nft to call the read/write methods directly instead of doing a global patch like this.

**Comment by ljharb** [comment]
That would also be a great long-term solution for nft :-)

(altho it'd still require next to update its bundle and/or stop bundling third party deps)
