### ISSUE TITLE
Output from TypeScript 4.4+ no longer traceable

### ISSUE THREAD

**Issue by styfle** [vercel/nft#288]
Source code:

```ts
import { join } from 'path'

const file = join(__dirname, 'file.txt')
```

[Output TS 4.3 or older](https://www.typescriptlang.org/play?target=6&module=1&ts=4.3.5#code/JYWwDg9gTgLgBAbzgKwsAdnAvnAZlCEOAcjAEMYALYgKBoGMJ0BneXYAGwFM4BeFNOgAUAfREATYFHRkQXADQl23AHQwAHjGIBKIA):

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const path_1 = require("path");
const file = path_1.join(__dirname, 'file.txt');
```

[Output TS 4.4 or newer](https://www.typescriptlang.org/play?target=6&module=1&ts=4.4.4#code/JYWwDg9gTgLgBAbzgKwsAdnAvnAZlCEOAcjAEMYALYgKBoGMJ0BneXYAGwFM4BeFNOgAUAfREATYFHRkQXADQl23AHQwAHjGIBKIA):

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const path_1 = require("path");
const file = (0, path_1.join)(__dirname, 'file.txt');
```

**Comment by styfle** [comment]
@guybedford Thoughts on how to solve this one? It seems like TS is doing this to avoid [this](https://2ality.com/2015/12/references.html)

**Comment by guybedford** [comment]
@styfle it should be relatively straightforward to substitute the `(0, path1.join)` as a pattern that is supported by the `path.join` style detection. It could be as simple as adding `(0, path.join)` support to the evaluator in supporting the result of this sequence expression being the result of the right side expression. That would be done by adding `SequenceExpression` here - https://github.com/vercel/nft/blob/main/src/utils/static-eval.ts. There may be other touch points but that's the first approach that comes to mind for a fix.

**Comment by styfle** [comment]
Makes sense! I created PR #289
