### ISSUE TITLE
Treat `fs-extra` as an alias to `fs` / `node:fs`

### ISSUE THREAD

**Issue by kachkaev** [vercel/nft#293]
I switched from plain `fs` to [`fs-extra`](https://www.npmjs.com/package/fs-extra) in [a project that uses Next.js and Vercel](https://github.com/blockprotocol/blockprotocol). After doing so I noticed that some Vercel lambdas ‘lost’ local files, which was really strange. The only solution I found was switching back to `const fs = require("fs")`.

About four months later I finally managed to discover this repo as well as `*.js.nft.json` files inside `.next/server/pages`. It all makes sense now 😅

Given the recent addition `node:fs` in https://github.com/vercel/nft/pull/285, would it be feasible to support `fs-extra` too? I understand that supporting every third-party lib is not worth it, but `fs-extra` is pretty big:

<img width="382" alt="Screenshot 2022-06-09 at 21 33 45" src="https://user-images.githubusercontent.com/608862/172939397-de178bde-f69a-41e3-a5f0-310cc5158875.png">

The mystery of ‘lost’ files in lambdas was bugging me for quite some time and I spent about two working days on figuring things out. If `fs-extra` was supported out of box before I switched to it, I’d be much less puzzled about Vercel! 🙂

What do you think? Happy to help with a PR or with testing!

**Comment by styfle** [comment]
Generally, this is already handled by `const file = path.join(process.cwd(), 'file.txt')` which would be analyzed prior to the actual fs call `const content = await fs.readFile(file)`.

Will path.join() work for your use case?

**Comment by kachkaev** [comment]
👋  @styfle! Interesting! Is there any way to use `path` with globs? E.g. here:

```ts
glob
  .sync(`${process.cwd()}/public/blocks/**/block-metadata.json`)
  .map((path: string): ExpandedBlockMetadata => { fs.readFileSync(path); })
```

**Comment by styfle** [comment]
It would be helpful if you can share a case that works with fs, but not fs-extra

**Comment by kachkaev** [comment]
I created a new test case in https://github.com/vercel/nft/pull/296. I wanted to fix the bug locally, but could not do `yarn install`. Might be related to my M1 mac and https://github.com/ranisalt/node-argon2/issues/305. I tried Node 14, 16 and 18, but no luck so far. Happy to dig into the problem further if you need my help!
