### ISSUE TITLE
snudown_es.js missing from snudown-js

### ISSUE THREAD

**Issue by ThomasGormley** [vercel/nft#305]
## Steps to reproduce
```bash
npm init -y
npm i snudown-js
echo 'require("snudown-js")' > index.js
npx nft build index.js
rm -rf node_modules/
node dist/index.js
```

## Error
```
Error: Cannot find module './snudown_es.js'
Require stack:
- snudown-error\dist\node_modules\snudown-js\dist\snudown.js
- snudown-error\dist\index.js
```

**Comment by styfle** [comment]
The dynamic require is not captured here:

https://unpkg.com/browse/snudown-js@3.2.3/dist/snudown.js

I think that the “esm” package is not used very often now that Node.js LTS has supported ESM proper for a few years.

**Comment by ThomasGormley** [comment]
Thanks.

I've created an issue to remove esm from snudown, however should nft be able to capture dynamic requires?

**Comment by ThomasGormley** [comment]
Snudown-js 4.0 has fixed this issue

 [breaking: drop "esm" dep and only publish native ES Modules build #37](https://github.com/erikdesjardins/snudown-js/pull/37)

Thanks for your help

**Comment by styfle** [comment]
We have static analysis to capture dynamic behavior but it’s best effort and this would likely require a special case. Since it’s already fixed upstream, I don’t think we need a special case.
