### ISSUE TITLE
Dependencies required through `module-alias` are treated as asset in 0.22.0

### ISSUE THREAD

**Issue by TonyRL** [vercel/nft#307]
## What's wrong

In the recent release of `nft@0.22.0` and Vercel internal builder update(<24hrs), users who deployed [RSSHub](https://github.com/DIYgod/RSSHub) on Vercel no longer works.
The function logs show that

```bash
2022-08-29T20:12:19.574Z	undefined	ERROR	Cannot find module 'got'
Require stack:
- /var/task/lib/utils/got.js
- /var/task/lib/middleware/parameter.js
- /var/task/lib/app.js
- /var/task/api/vercel.js
2022-08-29T20:12:19.574Z	undefined	ERROR	Did you forget to add it to "dependencies" in `package.json`?
RequestId: aecf3542-8033-4686-b5e8-30cdec421dc9 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Upon inspections, it's found that `nft@0.22.0` will categorise modules that are required through [`module-alias`](https://www.npmjs.com/package/module-alias) as `asset` and will be dropped. In the above log, `got` is treated as `asset` and removed from `node_modules`.

## Steps reproduce

Repo link to reproduce this issue [TonyRL/RSSHub-nft-repro](https://github.com/TonyRL/RSSHub-nft-repro)

1. Deploy it using <https://vercel.com/import/project?template=https://github.com/TonyRL/RSSHub-nft-repro>
2. Visit \<deployed domain\>/github/comments/vercel/nft/304
3. Expect the above logs

## Somes Observations

Since we also use `nft` as a source to minify our docker image, with a slight modification to the script, here are the `reasons` from `nft@0.21.0` and `nft@0.22.0`.
[reasons-v0.21.log](https://github.com/vercel/nft/files/9447867/reasons-v21.log)
[reasons-v0.22.log](https://github.com/vercel/nft/files/9447869/reasons-v22.log)

### Steps to reproduce these logs

1. `yarn`
2. `node scripts/docker/minify-docker.js > reasons-v0.22.log`
3. roll back to `nft@0.21.0` using `yarn add -D nft@0.21.0`
4. `node scripts/docker/minify-docker.js > reasons-v0.21.log`

### observations(cont.)

For simplicities, you can focus on `lib/utils/got.js`(our wrapper of `got`) only. In `nft@0.21.0`, `lib/utils/got.js` is a dependency and `got` is `resolve`:

```js
  'lib/utils/got.js' => {
    type: [ 'dependency' ],
    ignored: false,
    parents: Set(5) {
      'api/vercel.js',
      'lib/routes/docschina/jsweekly.js',
      'lib/routes/jinritoutiao/keyword.js',
      'lib/routes/shanbay/checkin.js',
      'lib/routes/universities/hit/jwc.js'
    }
  },
  ...
  'node_modules/got/package.json' => {
    type: [ 'resolve' ],
    ignored: false,
    parents: Set(27) {
      'lib/utils/got.js',
      'lib/routes/vscode/marketplace.js',
      'lib/routes/feed-the-beast/modpack.js',
      'lib/routes/gvm/index.js',
      'node_modules/got/dist/source/index.js',
      ...
    }
  },
```

In `nft@0.22.0`, `lib/utils/got.js` becomes an asset and `got` no longer appears in the `reasons` list:

```js
  'lib/utils/got.js' => {
    type: [ 'asset' ],
    ignored: false,
    parents: Set(1) { 'api/vercel.js' }
  },
```

If we require got using relative path instead of going through `module-alias` in `lib/middleware/parameter.js`(from `const got = require('@/utils/got');` to `const got = require('../utils/got');`) then `lib/utils/got.js` becomes one of the dependencies:

```js
  'lib/utils/got.js' => {
    type: [ 'asset', 'dependency' ],
    ignored: false,
    parents: Set(2) { 'api/vercel.js', 'lib/middleware/parameter.js' }
  },
```

and its dependency `got` will also be included in the `reasons`:
[reasons-v0.22-parameter.log](https://github.com/vercel/nft/files/9448083/reasons-v22-parameter.log)

```js
  'node_modules/got/package.json' => {
    type: [ 'resolve' ],
    ignored: false,
    parents: Set(24) {
      'lib/utils/got.js',
      'node_modules/got/dist/source/index.js',
      'node_modules/got/dist/source/create.js',
      ...
    }
  },
```

## Additional info

- `module-alias` works in the application by defining the alias in `lib/app.js`

```js
const moduleAlias = require('module-alias');
moduleAlias.addAlias('@', () => __dirname);
```

- Promoting the working deployment to production will not work as I believe Vercel's internal builder starts using `nft@0.22.0` in roughly <24hrs ago.

**Comment by styfle** [comment]
I realize this can take some time to update your code.

So in the meantime, you can make deployments with a previous version of Vercel CLI (and thus, the previous version of nft) by adding the environment variable `VERCEL_CLI_VERSION=vercel@28.1.4` to your Vercel Project.

I would not recommend that as a long term solution since it will prevent updates, but it could be a short term workaround and give you time to update your code to use package.json imports.

**Comment by TonyRL** [comment]
> However, there is a native feature of Node.js you can use to achieve the same result, [package.json "imports"](https://nodejs.org/api/packages.html#imports), which will work with nft.

Thanks for bringing this up. Looks like it's the way to go.

However, after updating the code to use subpath imports, I found out that `nft` does not support 'lazy-requiring' dependencies. This is confirmed by running `node scripts/docker/minify-docker.js > reasons.log` and `nft build api/vercel.js`.
I've also bumped the code in the reproducible repo [TonyRL/RSSHub-nft-repro](https://github.com/TonyRL/RSSHub-nft-repro).

For example, if you visit `<deployed domain>/1draw`, it will require `./routes/1draw/index.js` at runtime by `lazyloadRouteHandler` in `lib/router.js`. Since `nft` can't recognise 'lazy-required' files at build time(not even appears in `reasons`), it throws:
```bash
: Error in /1draw: Cannot find module './routes/1draw/index'
Require stack:
- /var/task/lib/router.js
- /var/task/lib/app.js
- /var/task/api/vercel.js
```

Again, similar behaviour also happens to `<deployed domain>/github/comments/vercel/nft/304`. But in this case, `lib/v2/github/comments.js` treated as `asset` and the functions log shows:
```bash
: Error in /github/comments/vercel/nft/304: Cannot find module 'markdown-it'
Require stack:
- /var/task/lib/v2/github/comments.js
- /var/task/lib/v2/github/router.js
- /var/task/node_modules/require-all/index.js
- /var/task/lib/v2router.js
- /var/task/lib/middleware/load-on-demand.js
- /var/task/lib/app.js
- /var/task/api/vercel.js
```

**Comment by styfle** [comment]
The `lazyloadRouteHandler()` isn't a Node.js, feature so its not statically analyzable.

If you use `require.resolve()` then nft can analyze the import.

This will work as you expect:

```diff
- router.get('/1draw', lazyloadRouteHandler('./routes/1draw/index'));
+ router.get('/1draw', lazyloadRouteHandler(require.resolve('./routes/1draw/index')));
```
