### ISSUE TITLE
`@vercel/nft` does not pick up platform-specific binaries for `sharp`

### ISSUE THREAD

**Issue by devunt** [vercel/nft#371]
Related:
- https://github.com/lovell/sharp/issues/3870
- https://github.com/getsentry/sentry-cli/issues/1849

`@vercel/nft` does not pick up platform-specific binary files while tracing dependencies.

For example, `sharp@0.33.0` [depends on](https://github.com/lovell/sharp/blob/main/lib/sharp.js#L16) `@img/sharp-{arch}` package, but the traced result only contains below paths.

```
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/package.json
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/index.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/constructor.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/input.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/resize.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/composite.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/colour.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/channel.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/utility.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/operation.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/output.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/is.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/sharp.js
node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/libvips.js
node_modules/.pnpm/sharp@0.33.0/node_modules/color
node_modules/.pnpm/sharp@0.33.0/node_modules/detect-libc
node_modules/.pnpm/sharp@0.33.0/node_modules/semver
```

This currently breaks every build on Vercel and any deployments that uses `@vercel/nft` as its tree shaking library.

**Comment by lovell** [comment]
The logic used for `esbuild` should solve this:

https://github.com/vercel/nft/blob/37811197975fef8a3cda7d17e436d217a510398c/src/utils/special-cases.ts#L32-L41

I guess it might be worth extracting this logic as a common helper function as the use of `optionalDependencies` for native binaries is an increasingly common pattern.

**Comment by styfle** [comment]
Indeed, the quickest path forward is to add a special case for `sharp` like the one for `esbuild` in `special-cases.ts`.

---

A proper fix would be updating the static analysis to handle the dynamic require.

We already support simple dynamic requires, such as:

```ts
const path = '@img/sharp-darwin-arm64/sharp.node';
const sharp = require(path);
```

Ideally, we could update that static analysis to handle the case of a for-loop, such as:

```ts
const paths = ['@img/sharp-darwin-arm64/sharp.node'];
for (const path of paths) {
  const sharp = require(path);
}
```

Source: https://github.com/lovell/sharp/blob/c80e92fa16b90a05ca604df17a3d58a87238b3ec/lib/sharp.js#L13-L30

**Comment by luke-hagar-sp** [comment]
From my understanding, this is causing all app deployments that require sentry to fail on Vercel. Is there any workaround for this issue?

**Comment by seanislegend** [comment]
I just ran into this issue. For anyone stuck, downgrading to `0.32.6` works.

**Comment by knd775** [comment]
I see that this issue was renamed to be `sharp` specific. The issue isn't specific to `sharp`, and is breaking every Sveltekit app on Vercel using Sentry as mentioned above.

**Comment by ZeldOcarina** [comment]
It's breaking all Astro deployments as well.. I had to downgrade sharp..

**Comment by lforst** [comment]
> I see that this issue was renamed to be `sharp` specific. The issue isn't specific to `sharp`, and is breaking every Sveltekit app on Vercel using Sentry as mentioned above.

Building onto this comment, considering this issue was renamed should we open a separate issue for the Sentry CLI issue? IMO it would be a step in the wrong direction since this issue affects pretty much all packages that ship their binaries in optional dependencies. It would probably even affect `swc`.

**Comment by alexbjorlig** [comment]
As a Vercel and Sentry customer, this affects us.

Can someone from Vercel come up with an expected date for fixing this issue? We are debating whether we should rollback, or wait for the fix 🤓

**Comment by knd775** [comment]
@styfle This seems to have been closed because the sharp special case PR was merged. This issue is still much larger than sharp.

**Comment by styfle** [comment]
If you create a new issue with the steps to reproduce, I'll take a look, thanks!

**Comment by benmccann** [comment]
For users of SvelteKit, I believe that setting `runtime: 'edge'` in `adapter-vercel` would avoid this issue and related issues by avoiding invoking `@vercel/nft`

https://kit.svelte.dev/docs/adapter-vercel#deployment-configuration

**Comment by knd775** [comment]
> For users of SvelteKit, I believe that setting `runtime: 'edge'` in `adapter-vercel` would avoid this issue and related issues by avoiding invoking `@vercel/nft`
> 
> https://kit.svelte.dev/docs/adapter-vercel#deployment-configuration

Sentry doesn't currently work with vercel edge functions because of another [vercel issue](https://github.com/vercel/vercel/issues/10829) related to source maps.

**Comment by knd775** [comment]
@styfle Would you be able to respond to these comments from @lforst? There's a bigger issue here than what you've acknowledged. We can create a reproduction, but I'm concerned that's only going to lead to another special case that doesn't address the underlying issue.

> I'd like to understand what's going on here. From my understanding `@vercel/nft` will only strip dependencies that are not used during _runtime_. During build-time, everything should be there.
> 
> We are seeing people having issues with our platform-specific binary on Vercel: [getsentry/sentry-cli#1849](https://github.com/getsentry/sentry-cli/issues/1849) However, this binary is only used during build-time. What is going on here? Is there something we can do from our end? Special casing sounds kinda dangerous to me because we need to avoid having the binary deployed because of size concerns.



> > I see that this issue was renamed to be `sharp` specific. The issue isn't specific to `sharp`, and is breaking every Sveltekit app on Vercel using Sentry as mentioned above.
> 
> Building onto this comment, considering this issue was renamed should we open a separate issue for the Sentry CLI issue? IMO it would be a step in the wrong direction since this issue affects pretty much all packages that ship their binaries in optional dependencies. It would probably even affect `swc`.

**Comment by styfle** [comment]
@knd775 I mentioned an idea for proper fix in my previous comment: https://github.com/vercel/nft/issues/371#issuecomment-1835148920

Without seeing the code causing sentry to fail, its hard to know if this will also solve it too. But ultimately, every failure of `@vercel/nft` is a dynamic require somewhere.

If you could create a new issue with the steps to reproduce, I could answer the question but right now I don't know what is going on without more information.

(looks like someone created without steps to reproduce here https://github.com/vercel/nft/issues/382)

**Comment by lforst** [comment]
Posting this here for visibility: We introduced a workaround in the latest version of the `@sentry/cli` package. See https://github.com/getsentry/sentry-cli/issues/1849#issuecomment-1873970001.

**Comment by lforst** [comment]
@styfle Nft is not doing anything wrong or buggy I believe. In my opinion, it is just not a good idea to let nft operate before the build has completed. During build we need particular entries in `optionalDependencies`, however during runtime they can be wiped. I don't fully understand why nft even needs to run before building except for maybe to optimize storage cost (?).

**Comment by styfle** [comment]
@lforst nft runs during the build to know which files need to be compiled and ignore the others

**Comment by lforst** [comment]
@styfle It appears though that `optionalDependencies` are not available at the time of compilation. Maybe this is entirely unrelated then?

**Comment by styfle** [comment]
Again, its hard to know what the root cause is without steps to reproduce the issue

**Comment by lforst** [comment]
I'll see if I can whip up a simple repro in the upcoming days!
