### ISSUE TITLE
bin/next not found and compiled/arg/index.js not found

### ISSUE THREAD

**Issue by webmandman** [vercel/nft#386]
I'm using the next.config.js option outpout: 'standalone' and its not copying the following module:
'next/dist/bin/next'

So I added it just to see if I can get it working, but bin/next requires this missing module:
'next/dist/compiled/arg/index.js'

what do I do?

My build is running github actions, if that helps. I'm copying missing modules from my local node modules to the production environment but it keeps going. ../lib/commands is also missing, then ../cli/next-start.

**Comment by styfle** [comment]
If you are using Next.js, please create an issue in the https://github.com/vercel/next.js repo and provide the steps to reproduce the problem, thanks!
