### ISSUE TITLE
Add support for `@datadog/pprof`

### ISSUE THREAD

**Issue by austinwoon** [vercel/nft#410]
When building with `output: standalone`, `@datadog/pprof` `prebuilds` gets excluded as the current AST logic introduced in https://github.com/vercel/nft/issues/391 does not handle the case where imports are assigned to a const. 

See `@datadog/pprof` codebase [here](https://github.com/DataDog/pprof-nodejs/blob/main/ts/src/heap-profiler-bindings.ts) on how they assign the CJS import of `node-gyp-build` to a variable, that way we cannot resolve the name to `node-gyp-build` just by inferring the AST node's first argument

## Suggested solution
Instead of modifying the conditionals to handle this case like in #391, just add a special case for `@datadog/pprof` to include the `prebuilds` folder. I have a fix up and will discuss the alternative in more detail here

**Comment by ragingwind** [comment]
Is there any progress at all? We have same issue

**Comment by austinwoon** [comment]
> Is there any progress at all? We have same issue

The PR is up awaiting review. You could comment there just to nudge it towards getting merged
