### ISSUE TITLE
Coding style differences in special-cases.ts

### ISSUE THREAD

**Issue by RogerHardiman** [vercel/nft#414]
Hi
I noticed some coding style differences in special-case.ts.
Just wanted to mention them in case someone wants to improve consistenys

1) SHIKI
```
shiki({ id, emitAssetDirectory }) {
    if (id.endsWith('/dist/index.js')) {            <----------------------- JUST CHECKS DIST/INDEX.JS
      emitAssetDirectory(resolve(dirname(id), '..', 'languages'));
      emitAssetDirectory(resolve(dirname(id), '..', 'themes'));
    }
  },
```

looking at all the other special cases I think it should have "skiki" in the "if (id.endsWith()...)" line

```
shiki({ id, emitAssetDirectory }) {
    if (id.endsWith('shiki/dist/index.js')) {     <------------------------ ALL OTHER SPECIAL CASES PUT PACKAGE NAME IN PATH EG SHIKI/DIST/INDEX.JS
      emitAssetDirectory(resolve(dirname(id), '..', 'languages'));
      emitAssetDirectory(resolve(dirname(id), '..', 'themes'));
    }
  },
```

2) In special.cases.ts there is an array of functions.
Some have the function name in single quotes, some don't use any quotes
eg
```
  'geo-tz'({ id, emitAsset }) {   <- SINGLE QUOTES
    if (id.endsWith('geo-tz/dist/geo-tz.js')) {
      emitAsset(resolve(dirname(id), '../data/geo.dat'));
    }
  },
  pixelmatch({ id, emitDependency }) {   <------ NO QUOTES
    if (id.endsWith('pixelmatch/index.js')) {
      emitDependency(resolve(dirname(id), 'bin/pixelmatch'));
    }
  },
```

It all transpiles into single quotes anyway so no problem.

Feel free to make this a Won't Fix. Just an observation.

**Comment by styfle** [comment]
The code is automatically formatted when you `npm run prettier-fix`. Perhaps filing an issue with `prettier` is necessary if you think this is a problem?

**Comment by RogerHardiman** [comment]
Many thanks
