### ISSUE TITLE
Deprecated subdependencies found in @mapbox/node-pre-gyp

### ISSUE THREAD

**Issue by cdwmhcc** [vercel/nft#421]
## Description

When installing dependencies for our project that uses `@vercel/nft`, we encountered warnings about deprecated subdependencies. These warnings are caused by the `@mapbox/node-pre-gyp` package, which is a dependency of `@vercel/nft`.

## Details

The following deprecated subdependencies are reported during `pnpm install`:

- `are-we-there-yet@2.0.0`
- `gauge@3.0.2`
- `inflight@1.0.6`
- `npmlog@5.0.1`

## Expected Behavior

Dependencies within `@vercel/nft` should not rely on deprecated packages to ensure better security and compatibility with modern development environments.

## Additional Information

- Node.js version: [20.13.1]
- pnpm version: [9.1.2]
- Operating System: [windows 11]

**Comment by styfle** [comment]
There is some related discussion here: https://github.com/vercel/nft/pull/407#issuecomment-2108830341

Would you like to submit a PR to fix it?

**Comment by benmccann** [comment]
>I wonder if we even need to include the dependency at all. I looked at argon2 to see how its used and its just a single function export:

Compare https://npmgraph.js.org/?q=argon2 vs https://npmgraph.js.org/?q=argon2@0.31.1

**Comment by benmccann** [comment]
I sent https://github.com/vercel/nft/pull/431 to upgrade `argon2`. I'm not sure what else is required to address this issue, but I believe this new version of argon2 should hopefully address the blockers and make this issue much easier to solve

**Comment by benmccann** [comment]
I see. That makes much more sense to me. Thanks!

It's not exactly clear to me that `find` is easily replaceable though it would be awesome if someone can figure out how to do that. In the meantime I'll work on cleaning up `@mapbox/node-pre-gyp`. I'll track that here:

- https://github.com/mapbox/node-pre-gyp/pull/721
- https://github.com/mapbox/node-pre-gyp/pull/721

**Comment by benmccann** [comment]
`argon2` switched from `@mapbox/node-pre-gyp` to `node-gyp-build` here:
https://github.com/ranisalt/node-argon2/commit/b47602840a259946039db8526ddd182d1430f634#diff-bc704b883867dea430073059d0e3061c8ac87c037826b06007646f667777916d

The latter library is dramatically lighter. I wonder if we could make the same switch here

**Comment by benmccann** [comment]
@styfle based on the link from my past comment, do you think something like this might work?

![Screenshot from 2024-06-30 20-37-33](https://github.com/vercel/nft/assets/322311/91e7b888-476a-4d84-9c5d-1bfeca725226)

It looks like `argon2` was able to do something similar, but when I create a dummy `find` method that returns `null` I don't get any extra failing tests (I have 6 that fail for me both on `main` and with a clearly broken implementation), so I'm not overly confident in the fix. I'm wholly unfamiliar with `nft` so don't know if I can put together and test a fix, but I hope that discovering the `argon2` implementation uses `node-gyp-build` to do the same as `@mapbox/node-pre-gyp`'s `find` will be enough to let you address this.

**Comment by styfle** [comment]
nft supports both `node-gyp-build` and `@mapbox/node-pre-gyp` because it needs to work on any version of any npm package

**Comment by vhovorun** [comment]
@styfle @benmccann Hey guys, sorry for pinging u but any updates on this one?

**Comment by KillyMXI** [comment]
Current latest version of `@mapbox/node-pre-gyp` is 1.0.11 (from 2024-07-03)
`@vercel/nft` still depends on 1.0.5.

Is there a reason to stick with the old version? Otherwise, just bumping the version would resolve some warnings.

**Comment by styfle** [comment]
Bumping in PR https://github.com/vercel/nft/pull/451

Although none of [these upstream PRs](https://github.com/vercel/nft/issues/421#issuecomment-2195148286) have landed yet so I don't think it will make a difference

**Comment by nanobugsbozbitcH** [comment]
> ## Description
> When installing dependencies for our project that uses `@vercel/nft`, we encountered warnings about deprecated subdependencies. These warnings are caused by the `@mapbox/node-pre-gyp` package, which is a dependency of `@vercel/nft`.
> 
> ## Details
> The following deprecated subdependencies are reported during `pnpm install`:
> 
> * `are-we-there-yet@2.0.0`
> * `gauge@3.0.2`
> * `inflight@1.0.6`
> * `npmlog@5.0.1`
> 
> ## Expected Behavior
> Dependencies within `@vercel/nft` should not rely on deprecated packages to ensure better security and compatibility with modern development environments.
> 
> ## Additional Information
> * Node.js version: [20.13.1]
> * pnpm version: [9.1.2]
> * Operating System: [windows 11]

Nanobots

**Comment by nanobugsbozbitcH** [comment]
> Bumping in PR #451 but it won't make a difference for consumers since the `^` will still match the latest version of the `1.x.y`.
> 
> Also note that none of [these upstream PRs](https://github.com/vercel/nft/issues/421#issuecomment-2195148286) have landed yet.

Nanobots

**Comment by HummingMind** [comment]
Deprecated warnings are gone in version 2.0.0-rc.0 that was just published.
