### ISSUE TITLE
Does not include registered ESM loader hooks

### ISSUE THREAD

**Issue by timfish** [vercel/nft#428]
`package.json`
```json
{
  "type": "module",
  "dependencies": {
    "import-in-the-middle": "^1.8.1"
  },
  "devDependencies": {
    "@vercel/nft": "^0.27.2"
  }
}
```
`test.js`
```ts
import { register } from 'module';

register('import-in-the-middle/hook.mjs', import.meta.url);
```
`build.js`
```ts
import { nodeFileTrace } from '@vercel/nft';
const { fileList } = await nodeFileTrace(['./test.js']);
console.log(fileList)
```

Running `> node build.js`
Outputs `Set(1) { 'test.js' }`

But `import-in-the-middle/hook.mjs` and all of it's dependencies should be included.

**Comment by s1gr1d** [comment]
This also affects nitropack (and therefore also Nuxt). The `.output` build folder of nuxt does not include `import-in-the-middle/hook.mjs` which can lead to the same error.

I am not a 100% sure how nuxt builds nuxt apps under the hood but `nodeFileTrace` is used here in nitropack: https://github.com/unjs/nitro/blob/v2/src/rollup/plugins/externals.ts

@pi0 `@vercel/nft` should probably be updated after this is merged: https://github.com/vercel/nft/pull/429

**Comment by pi0** [comment]
Thanks for the heads up @s1gr1d. Nitro has a caret `^` dependency on `@vercel/nft` which means as long as any fix or enhancement lands in a semver-minor/patch version of this package, updating your lock file is enough to get the fix. 

Nevertheless feel free to report an issue downstream in nitropack repo if you can assemble a minimal nitro reproduction 🙏🏼
